name: ci-test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name : Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.24
        id: go

      - name : check out code
        uses: actions/checkout@v2

      - name: Test
        run: make test
